/**
 * Academy checkpoint / fault library — one distinct definition set per shot type.
 *
 * This is the knowledge core of the Academy feature. Each shot type defines:
 *   - phases:   the key positions the video is segmented into
 *   - metrics:  measurable 2D pose quantities with benchmark ranges
 *   - faults:   detectable deviations, each with plain-language coaching copy,
 *               a drill, and search keywords used to match creator videos
 *
 * Every metric here is honestly computable from 17-keypoint 2D pose data
 * (MoveNet/COCO). Where a true 3D quantity (e.g. shoulder turn) is
 * approximated, the metric is a documented 2D proxy — e.g. apparent
 * shoulder-line compression on a face-on view.
 *
 * Metric values are produced by metrics.js; fault predicates below are
 * evaluated by analyze.js against those values.
 *
 * angle: which camera angle a metric/fault needs — 'face_on', 'down_the_line',
 * or 'any'. Metrics whose angle doesn't match the upload are skipped, never
 * guessed.
 */

const SHOT_TYPE_IDS = ['driving', 'iron', 'bunker', 'chipping', 'putting'];

// ---------------------------------------------------------------------------
// DRIVING — widest arc, biggest turn, ball struck on the up.
// ---------------------------------------------------------------------------

const DRIVING = {
  id: 'driving',
  label: 'Driving',
  swingClass: 'full',
  summary:
    'Full swing with the longest club. Analysis focuses on a big backswing turn, stable head and lower body, spine tilt away from the target at impact, and a balanced finish.',
  phases: [
    { id: 'address', label: 'Address', description: 'Setup before the takeaway starts.' },
    { id: 'takeaway', label: 'Takeaway', description: 'First move — club and hands start back.' },
    { id: 'top', label: 'Top of Backswing', description: 'Highest point of the hands, full turn loaded.' },
    { id: 'impact', label: 'Impact', description: 'Hands return to the strike zone.' },
    { id: 'finish', label: 'Finish', description: 'Balanced full follow-through.' },
  ],
  tempo: { idealRatio: 3.0, min: 2.2, max: 3.8, label: 'Backswing : downswing time. Tour average is around 3:1.' },
  metrics: [
    {
      id: 'shoulder_turn_top',
      label: 'Shoulder turn at top',
      unit: '°',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 70, ideal: 90, max: 110 },
      description: '2D proxy: how far the shoulder line has rotated out of the camera plane at the top. Bigger turn = more stored power.',
      progressMetric: true,
    },
    {
      id: 'hip_turn_top',
      label: 'Hip turn at top',
      unit: '°',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 30, ideal: 45, max: 60 },
      description: '2D proxy of hip rotation at the top. Roughly half the shoulder turn creates coil.',
    },
    {
      id: 'head_sway',
      label: 'Head sway (backswing)',
      unit: '% torso',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 0, ideal: 5, max: 15 },
      description: 'Sideways head drift away from the target during the backswing, as a % of torso length. A stable head keeps the strike centred.',
      progressMetric: true,
    },
    {
      id: 'hip_sway',
      label: 'Hip sway (backswing)',
      unit: '% torso',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 0, ideal: 6, max: 18 },
      description: 'Lateral hip slide away from the target during the backswing. Turn, don\'t slide.',
    },
    {
      id: 'spine_tilt_impact',
      label: 'Spine tilt at impact',
      unit: '°',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 5, ideal: 12, max: 25 },
      description: 'Upper body tilted away from the target at impact — essential with driver to hit up on the ball.',
      progressMetric: true,
    },
    {
      id: 'spine_tilt_top',
      label: 'Spine tilt at top',
      unit: '°',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: -12, ideal: -4, max: 5 },
      description: 'Signed spine lean at the top (negative = away from target). Leaning toward the target at the top is a reverse pivot.',
    },
    {
      id: 'lead_arm_bend_top',
      label: 'Lead arm bend at top',
      unit: '°',
      angle: 'any',
      phase: 'top',
      benchmark: { min: 0, ideal: 8, max: 25 },
      description: 'How far the lead arm folds at the top (0° = perfectly straight). A little bend is fine; a collapsed arm narrows the arc.',
    },
    {
      id: 'weight_forward_impact',
      label: 'Weight transfer at impact',
      unit: '% torso',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 2, ideal: 10, max: 25 },
      description: 'How far the hips have shifted toward the target at impact versus address. Positive = pressure moving forward.',
    },
    {
      id: 'chicken_wing',
      label: 'Lead elbow bend post-impact',
      unit: '°',
      angle: 'face_on',
      phase: 'finish',
      benchmark: { min: 0, ideal: 15, max: 45 },
      description: 'Lead elbow fold just after impact. A sharply folded ("chicken wing") elbow usually means a held-off, weaker release.',
    },
    {
      id: 'posture_bend_address',
      label: 'Posture (forward bend) at address',
      unit: '°',
      angle: 'down_the_line',
      phase: 'address',
      benchmark: { min: 25, ideal: 35, max: 45 },
      description: 'Forward bend from vertical at setup, seen down the line. Athletic tilt lets the arms swing freely.',
    },
    {
      id: 'posture_loss_impact',
      label: 'Posture change at impact',
      unit: '°',
      angle: 'down_the_line',
      phase: 'impact',
      benchmark: { min: -12, ideal: 0, max: 8 },
      description: 'Change in forward bend between address and impact (positive = standing up out of the shot).',
      progressMetric: true,
    },
    {
      id: 'early_extension',
      label: 'Early extension',
      unit: '% torso',
      angle: 'down_the_line',
      phase: 'impact',
      benchmark: { min: -5, ideal: 2, max: 10 },
      description: 'How far the hips push toward the ball line through the downswing. Thrusting at the ball forces the arms to bail out.',
    },
    {
      id: 'head_dip',
      label: 'Head dip into impact',
      unit: '% torso',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: -8, ideal: 0, max: 10 },
      description: 'Vertical head movement between address and impact (positive = dipping down).',
    },
    {
      id: 'finish_balance',
      label: 'Finish balance',
      unit: '% torso',
      angle: 'face_on',
      phase: 'finish',
      benchmark: { min: 0, ideal: 10, max: 30 },
      description: 'How close the body centre finishes over the lead leg. A committed drive ends stacked on the front foot.',
    },
    {
      id: 'tempo_ratio',
      label: 'Tempo ratio',
      unit: ':1',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 2.2, ideal: 3.0, max: 3.8 },
      description: 'Backswing time divided by downswing time. Around 3:1 keeps the transition smooth.',
      progressMetric: true,
    },
  ],
  faults: [
    {
      tag: 'driving-sway',
      name: 'Swaying off the ball',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'hip_sway', when: 'above', value: 18 },
      description: 'Your hips slide away from the target in the backswing instead of turning. That moves the low point around and costs you a consistent strike.',
      tip: 'Feel like your trail hip turns behind you rather than sliding sideways. Your trail leg is a post — load into it, don\'t lean past it.',
      drill: 'Place an alignment stick in the ground just outside your trail hip at address. Make backswings without bumping it.',
      searchKeywords: ['stop swaying golf swing', 'hip turn backswing drill', 'rotate hips backswing driver'],
    },
    {
      tag: 'driving-head-sway',
      name: 'Head drifting off the ball',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'head_sway', when: 'above', value: 15 },
      description: 'Your head moves noticeably away from the target during the backswing, which makes returning the club to the ball a timing exercise.',
      tip: 'Keep your head centred while your shoulders turn around it. Turn "in a barrel" rather than shifting sideways.',
      drill: 'Set up with your lead cheek lightly touching a wall shadow or door frame and rehearse backswings without losing contact.',
      searchKeywords: ['keep head still golf swing', 'stable head backswing drill', 'head movement golf swing fix'],
    },
    {
      tag: 'driving-reverse-pivot',
      name: 'Reverse pivot',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'spine_tilt_top', when: 'above', value: 5 },
      description: 'At the top, your upper body leans toward the target instead of loading behind the ball — the classic reverse pivot. It usually leads to a weak, steep downswing.',
      tip: 'At the top of the backswing your lead shoulder should feel over your trail thigh, not over your lead foot.',
      drill: 'Hit balls with your feet together to feel a centred turn, then rebuild your normal stance keeping that feeling.',
      searchKeywords: ['reverse pivot golf fix', 'load trail side backswing', 'weight shift backswing drill'],
    },
    {
      tag: 'driving-flat-shoulder-turn',
      name: 'Incomplete shoulder turn',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'shoulder_turn_top', when: 'below', value: 70 },
      description: 'Your shoulder turn at the top is short of a full coil, which limits width and clubhead speed with the driver.',
      tip: 'Turn your lead shoulder behind the ball. Feel like your back faces the target at the top.',
      drill: 'Cross your arms over your chest and rehearse turning your lead shoulder over your trail thigh — hold for two seconds, repeat ten times.',
      searchKeywords: ['bigger shoulder turn golf', 'increase backswing turn driver', 'full shoulder turn drill'],
    },
    {
      tag: 'driving-hang-back',
      name: 'Hanging back at impact',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'weight_forward_impact', when: 'below', value: 2 },
      description: 'Your weight hasn\'t moved toward the target by impact. With driver you still need pressure forward even though the ball is struck on the up.',
      tip: 'Start the downswing by re-planting into the lead foot before the arms come down.',
      drill: 'Step-through drill: hit half-speed drivers and let your trail foot walk through after impact — impossible to do hanging back.',
      searchKeywords: ['weight transfer downswing driver', 'stop hanging back golf', 'shift pressure lead side drill'],
    },
    {
      tag: 'driving-no-spine-tilt',
      name: 'No spine tilt at impact',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'spine_tilt_impact', when: 'below', value: 5 },
      description: 'Your upper body is level or ahead of the ball at impact. With driver you want the spine tilted slightly away from the target to launch the ball up.',
      tip: 'At impact, feel your lead ear staying behind the ball while your hips drive forward.',
      drill: 'Tee the ball high and rehearse impact positions in slow motion: hips forward, head back, trail shoulder lower.',
      searchKeywords: ['spine tilt driver impact', 'hit up on driver drill', 'launch driver higher setup'],
    },
    {
      tag: 'driving-early-extension',
      name: 'Early extension',
      angle: 'down_the_line',
      phase: 'impact',
      detect: { metric: 'early_extension', when: 'above', value: 10 },
      description: 'Your hips thrust toward the ball in the downswing, forcing you to stand up and flip the hands. It\'s one of the most common amateur power leaks.',
      tip: 'Feel your lead glute staying "on the wall" behind you as you rotate through impact.',
      drill: 'Set up with your backside touching a chair or wall and hit half shots keeping contact until after impact.',
      searchKeywords: ['early extension golf fix', 'stop standing up golf swing', 'keep posture downswing drill'],
    },
    {
      tag: 'driving-posture-loss',
      name: 'Losing posture',
      angle: 'down_the_line',
      phase: 'impact',
      detect: { metric: 'posture_loss_impact', when: 'above', value: 8 },
      description: 'Your forward bend at impact is much more upright than at address — you\'re coming out of the shot before the ball has gone.',
      tip: 'Stay in your address inclination until the ball is gone; let the trail shoulder work down and through, not up and over.',
      drill: 'Practice swings brushing the grass on a line: if you stand up, the club never reaches the turf.',
      searchKeywords: ['maintain posture golf swing', 'losing spine angle fix', 'stay in posture drill'],
    },
    {
      tag: 'driving-collapsed-lead-arm',
      name: 'Collapsed lead arm at the top',
      angle: 'any',
      phase: 'top',
      detect: { metric: 'lead_arm_bend_top', when: 'above', value: 25 },
      description: 'Your lead arm folds sharply at the top, narrowing the swing arc and costing effortless speed.',
      tip: 'Feel width, not length — push your hands away from your head at the top rather than lifting them behind it.',
      drill: 'Make backswings holding a towel between your lead armpit and chest without dropping it; stop when the arm wants to fold.',
      searchKeywords: ['straight lead arm backswing', 'wide backswing arc drill', 'collapsed left arm golf fix'],
    },
    {
      tag: 'driving-chicken-wing',
      name: 'Chicken wing through impact',
      angle: 'face_on',
      phase: 'finish',
      detect: { metric: 'chicken_wing', when: 'above', value: 45 },
      description: 'Your lead elbow folds up and out just after impact instead of extending. It usually accompanies a slice-pattern, held-off release.',
      tip: 'Let both arms straighten past the ball — feel like you\'re throwing the clubhead down the fairway.',
      drill: 'Swing a towel or headcover and make it "snap" well past where the ball would be, both arms long.',
      searchKeywords: ['chicken wing golf fix', 'extend arms through impact', 'release drill slice fix driver'],
    },
    {
      tag: 'driving-quick-tempo',
      name: 'Rushed transition',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'tempo_ratio', when: 'below', value: 2.2 },
      description: 'Your downswing starts before the backswing finishes — the ratio between backswing and downswing time is well below the smooth 3:1 benchmark.',
      tip: 'Give the club time to arrive at the top. Count "one-and-two" — the ball is struck on "two", never on "and".',
      drill: 'Swing at 70% and exaggerate a one-second pause at the top for ten balls, then blend it back to full speed.',
      searchKeywords: ['golf tempo drill 3 to 1', 'smooth transition downswing', 'stop rushing downswing'],
    },
    {
      tag: 'driving-off-balance-finish',
      name: 'Off-balance finish',
      angle: 'face_on',
      phase: 'finish',
      detect: { metric: 'finish_balance', when: 'above', value: 30 },
      description: 'You\'re not finishing stacked over your lead leg — a sign the swing\'s effort exceeded its balance.',
      tip: 'Swing at a speed you can hold the finish for three full seconds, every time.',
      drill: 'Hit drivers holding every finish until the ball lands. If you can\'t hold it, drop 10% speed until you can.',
      searchKeywords: ['balanced finish golf drill', 'hold your finish golf', 'swing in balance driver'],
    },
  ],
  recordingTips: {
    face_on: 'Stand the camera chest-high, 3–4 m away, directly facing you. Whole body and club in frame at address and at the top.',
    down_the_line: 'Camera chest-high on the ball-target line behind your hands. Keep your whole body and the club in frame throughout.',
  },
};

// ---------------------------------------------------------------------------
// IRON SWING — ball-first contact, compression, controlled flight.
// ---------------------------------------------------------------------------

const IRON = {
  id: 'iron',
  label: 'Iron Swing',
  swingClass: 'full',
  summary:
    'Full swing hitting down on the ball. Analysis focuses on a centred turn, weight clearly forward at impact, hands leading the strike, and holding posture through the shot.',
  phases: [
    { id: 'address', label: 'Address', description: 'Setup before the takeaway starts.' },
    { id: 'takeaway', label: 'Takeaway', description: 'First move away from the ball.' },
    { id: 'top', label: 'Top of Backswing', description: 'Highest hand point, turn completed.' },
    { id: 'impact', label: 'Impact', description: 'Hands back to the ball — the moment of truth.' },
    { id: 'finish', label: 'Finish', description: 'Full, balanced follow-through.' },
  ],
  tempo: { idealRatio: 3.0, min: 2.2, max: 3.8, label: 'Backswing : downswing time. Around 3:1, same as the driver.' },
  metrics: [
    {
      id: 'shoulder_turn_top',
      label: 'Shoulder turn at top',
      unit: '°',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 65, ideal: 85, max: 105 },
      description: '2D proxy of shoulder rotation at the top. Irons need a full but controlled turn.',
      progressMetric: true,
    },
    {
      id: 'head_sway',
      label: 'Head sway (backswing)',
      unit: '% torso',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 0, ideal: 4, max: 12 },
      description: 'Sideways head drift in the backswing. Iron strikes live and die on a stable centre.',
      progressMetric: true,
    },
    {
      id: 'hip_sway',
      label: 'Hip sway (backswing)',
      unit: '% torso',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: 0, ideal: 5, max: 15 },
      description: 'Lateral hip slide away from the target going back.',
    },
    {
      id: 'weight_forward_impact',
      label: 'Weight forward at impact',
      unit: '% torso',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 6, ideal: 14, max: 28 },
      description: 'Hip shift toward the target at impact. Irons need clearly more forward pressure than driver for ball-first contact.',
      progressMetric: true,
    },
    {
      id: 'hands_forward_impact',
      label: 'Hands ahead at impact',
      unit: '% torso',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 0, ideal: 8, max: 20 },
      description: '2D proxy for shaft lean: how far the hands are ahead of the body centre at impact. Hands leading = compression.',
      progressMetric: true,
    },
    {
      id: 'spine_tilt_impact',
      label: 'Spine tilt at impact',
      unit: '°',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 0, ideal: 6, max: 15 },
      description: 'Slight tilt away from the target at impact — less than driver; too much means hanging back.',
    },
    {
      id: 'spine_tilt_top',
      label: 'Spine tilt at top',
      unit: '°',
      angle: 'face_on',
      phase: 'top',
      benchmark: { min: -12, ideal: -4, max: 5 },
      description: 'Signed spine lean at the top (negative = away from target). Toward-target lean is a reverse pivot.',
    },
    {
      id: 'lead_arm_bend_top',
      label: 'Lead arm bend at top',
      unit: '°',
      angle: 'any',
      phase: 'top',
      benchmark: { min: 0, ideal: 10, max: 28 },
      description: 'Lead arm fold at the top (0° = dead straight).',
    },
    {
      id: 'chicken_wing',
      label: 'Lead elbow bend post-impact',
      unit: '°',
      angle: 'face_on',
      phase: 'finish',
      benchmark: { min: 0, ideal: 15, max: 45 },
      description: 'Lead elbow fold just after the strike. Folding early usually means a scoopy, weak release.',
    },
    {
      id: 'posture_bend_address',
      label: 'Posture (forward bend) at address',
      unit: '°',
      angle: 'down_the_line',
      phase: 'address',
      benchmark: { min: 28, ideal: 38, max: 48 },
      description: 'Forward bend at setup seen down the line — irons sit closer, so posture is slightly more bent than driver.',
    },
    {
      id: 'posture_loss_impact',
      label: 'Posture change at impact',
      unit: '°',
      angle: 'down_the_line',
      phase: 'impact',
      benchmark: { min: -10, ideal: 0, max: 6 },
      description: 'Change in forward bend from address to impact (positive = standing up).',
      progressMetric: true,
    },
    {
      id: 'early_extension',
      label: 'Early extension',
      unit: '% torso',
      angle: 'down_the_line',
      phase: 'impact',
      benchmark: { min: -5, ideal: 2, max: 8 },
      description: 'Hip thrust toward the ball line in the downswing — tighter tolerance than driver because the ball is on the ground.',
    },
    {
      id: 'head_dip',
      label: 'Head dip into impact',
      unit: '% torso',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: -6, ideal: 0, max: 8 },
      description: 'Vertical head movement from address to impact. Dipping steepens everything; rising thins it.',
    },
    {
      id: 'tempo_ratio',
      label: 'Tempo ratio',
      unit: ':1',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 2.2, ideal: 3.0, max: 3.8 },
      description: 'Backswing time over downswing time.',
      progressMetric: true,
    },
  ],
  faults: [
    {
      tag: 'iron-scooping',
      name: 'Scooping — hands behind at impact',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'hands_forward_impact', when: 'below', value: 0 },
      description: 'Your hands are level with or behind the ball at impact, adding loft instead of compressing the ball. Contact will alternate between thin and fat.',
      tip: 'Feel the lead wrist flat and the hands past the ball before the clubhead catches up.',
      drill: 'Hit punch shots with a 9-iron finishing with hands waist-high and the shaft leaning toward the target.',
      searchKeywords: ['stop scooping irons', 'shaft lean impact drill', 'compress the golf ball irons', 'hands ahead at impact'],
    },
    {
      tag: 'iron-hang-back',
      name: 'Hanging back',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'weight_forward_impact', when: 'below', value: 6 },
      description: 'Your pressure is still on the trail side at impact. With irons the bottom of the swing arc then falls behind the ball — fat and thin strikes follow.',
      tip: 'By impact, feel 80% of your pressure into the lead foot with your chest over the ball.',
      drill: 'Hit balls with your trail heel raised on a half-flip flop or towel — you can\'t hang back on it.',
      searchKeywords: ['weight forward iron strike', 'stop hitting fat shots', 'strike irons pure weight shift'],
    },
    {
      tag: 'iron-sway',
      name: 'Swaying off the ball',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'hip_sway', when: 'above', value: 15 },
      description: 'Your hips slide away from the target going back rather than turning, moving the swing\'s low point off the ball.',
      tip: 'Load into the inside of your trail foot; your trail hip should turn back, not slide out.',
      drill: 'Practice with a golf bag just outside your trail hip — turn without touching it.',
      searchKeywords: ['stop swaying golf swing', 'centered pivot iron drill', 'hip turn not slide golf'],
    },
    {
      tag: 'iron-reverse-pivot',
      name: 'Reverse pivot',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'spine_tilt_top', when: 'above', value: 5 },
      description: 'Upper body leaning toward the target at the top. The downswing then falls back away from the target — the exact opposite of an iron\'s forward strike.',
      tip: 'Feel your sternum stay over or slightly behind the ball at the top, never ahead of it.',
      drill: 'Feet-together swings: ten half shots feeling the turn stay centred between your feet.',
      searchKeywords: ['reverse pivot golf fix', 'load backswing correctly', 'weight shift drill irons'],
    },
    {
      tag: 'iron-early-extension',
      name: 'Early extension',
      angle: 'down_the_line',
      phase: 'impact',
      detect: { metric: 'early_extension', when: 'above', value: 8 },
      description: 'Your hips move toward the ball in the downswing, standing you up through impact and blocking the arms from swinging freely.',
      tip: 'Keep your belt buckle rotating, not thrusting — trail pocket works behind you through the strike.',
      drill: 'Chair drill: backside brushing a chair at address, keep light contact until the ball is gone.',
      searchKeywords: ['early extension golf fix', 'hips toward ball downswing', 'rotate dont thrust golf drill'],
    },
    {
      tag: 'iron-posture-loss',
      name: 'Losing posture',
      angle: 'down_the_line',
      phase: 'impact',
      detect: { metric: 'posture_loss_impact', when: 'above', value: 6 },
      description: 'You stand up out of your address tilt before impact — the low point rises with you and thin contact follows.',
      tip: 'Hold your forward bend until the ball has gone; feel your chest staying "down and through".',
      drill: 'Shadow drill: set up with the sun behind you, head shadow on a spot — keep it there until impact.',
      searchKeywords: ['maintain posture irons', 'stop standing up through impact', 'keep spine angle drill'],
    },
    {
      tag: 'iron-head-sway',
      name: 'Head drifting off the ball',
      angle: 'face_on',
      phase: 'top',
      detect: { metric: 'head_sway', when: 'above', value: 12 },
      description: 'Your head moves noticeably off the ball going back. Irons are precision clubs — the centre must stay quiet.',
      tip: 'Turn your shoulders around a still head; feel your nose pointing at the ball to the top.',
      drill: 'Have a friend hold a club grip lightly against your lead-side hair at address — turn without pushing into it.',
      searchKeywords: ['keep head still iron swing', 'quiet head golf drill', 'consistent iron strikes head movement'],
    },
    {
      tag: 'iron-chicken-wing',
      name: 'Chicken wing through impact',
      angle: 'face_on',
      phase: 'finish',
      detect: { metric: 'chicken_wing', when: 'above', value: 45 },
      description: 'The lead elbow folds up immediately after impact instead of extending — a hold-off pattern that leaks loft and speed.',
      tip: 'Feel both arms long and the clubhead released past your body after the strike.',
      drill: 'Swing with a glove tucked under the lead armpit through impact — it should stay put until the follow-through.',
      searchKeywords: ['chicken wing golf fix', 'extension through impact drill', 'release the club irons'],
    },
    {
      tag: 'iron-collapsed-lead-arm',
      name: 'Collapsed lead arm at the top',
      angle: 'any',
      phase: 'top',
      detect: { metric: 'lead_arm_bend_top', when: 'above', value: 28 },
      description: 'Your lead arm folds sharply at the top, shortening the arc and making low-point control harder.',
      tip: 'Shorter and wider beats longer and bent — stop the backswing where the lead arm stays comfortably straight.',
      drill: 'Make three-quarter backswings in a mirror, stopping at the first hint of elbow fold.',
      searchKeywords: ['lead arm straight backswing', 'compact backswing drill', 'shorten backswing golf'],
    },
    {
      tag: 'iron-head-dip',
      name: 'Head dipping into impact',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'head_dip', when: 'above', value: 8 },
      description: 'Your head drops toward the ball coming down, steepening the strike and risking fat contact.',
      tip: 'Maintain your height through the downswing — the feeling is "tall chest, heavy feet".',
      drill: 'Slow-motion swings under a doorway bar or club held just above your head: turn through without touching it.',
      searchKeywords: ['head dip golf swing fix', 'maintain height downswing', 'fat shots head drop'],
    },
    {
      tag: 'iron-quick-tempo',
      name: 'Rushed transition',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'tempo_ratio', when: 'below', value: 2.2 },
      description: 'The downswing starts before the backswing has finished. Strike quality with irons collapses when the ratio drops far below 3:1.',
      tip: 'Complete the turn. Feel the club "set" at the top before anything moves toward the ball.',
      drill: 'Say "swing... and... strike" out loud — the ball is hit on "strike", never earlier.',
      searchKeywords: ['golf tempo drill irons', 'smooth transition golf swing', '3 to 1 tempo golf'],
    },
  ],
  recordingTips: {
    face_on: 'Camera chest-high, 3–4 m away, square to your chest. Ball and full body in frame.',
    down_the_line: 'Camera chest-high, directly behind the ball-target line, level with your hands.',
  },
};

// ---------------------------------------------------------------------------
// BUNKER — splash technique: stable legs, early hinge, commit through sand.
// ---------------------------------------------------------------------------

const BUNKER = {
  id: 'bunker',
  label: 'Bunker',
  swingClass: 'short',
  summary:
    'Greenside splash shot. Analysis focuses on a wide stable base, flexed knees held through the strike, an early wrist set, and — above all — accelerating through the sand to a full finish.',
  phases: [
    { id: 'address', label: 'Address', description: 'Wide, low setup with the face open.' },
    { id: 'top', label: 'Top of Backswing', description: 'Steep, early-hinged backswing.' },
    { id: 'impact', label: 'Strike (splash)', description: 'Club enters the sand behind the ball.' },
    { id: 'finish', label: 'Finish', description: 'Committed follow-through — sand and ball come out together.' },
  ],
  tempo: { idealRatio: 1.6, min: 1.0, max: 2.4, label: 'Backswing : downswing time. Splash shots are more even-paced than full swings.' },
  metrics: [
    {
      id: 'stance_width',
      label: 'Stance width',
      unit: '× shoulders',
      angle: 'face_on',
      phase: 'address',
      benchmark: { min: 1.1, ideal: 1.35, max: 1.7 },
      description: 'Ankle spread relative to shoulder width. Bunker shots need a wide, planted base in soft sand.',
    },
    {
      id: 'knee_flex_address',
      label: 'Knee flex at address',
      unit: '°',
      angle: 'any',
      phase: 'address',
      benchmark: { min: 15, ideal: 25, max: 40 },
      description: 'How much the knees are flexed at setup (0° = straight legs). Sitting into the sand lowers the swing\'s bottom.',
    },
    {
      id: 'knee_flex_loss',
      label: 'Leg straightening at strike',
      unit: '°',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: -8, ideal: 0, max: 10 },
      description: 'Change in knee flex between address and the strike (positive = legs straightening). Stand up and you blade it.',
      progressMetric: true,
    },
    {
      id: 'early_hinge',
      label: 'Early wrist set',
      unit: '% torso',
      angle: 'any',
      phase: 'top',
      benchmark: { min: 5, ideal: 15, max: 35 },
      description: '2D proxy: how quickly the hands rise relative to the arms early in the backswing. Splash shots hinge almost immediately.',
      progressMetric: true,
    },
    {
      id: 'head_sway',
      label: 'Head movement',
      unit: '% torso',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 0, ideal: 4, max: 12 },
      description: 'Total head drift through the shot. The entry point in the sand must be repeatable, so the centre stays quiet.',
    },
    {
      id: 'weight_forward_address',
      label: 'Weight forward at address',
      unit: '% stance',
      angle: 'face_on',
      phase: 'address',
      benchmark: { min: 5, ideal: 15, max: 30 },
      description: 'How much the body centre favours the lead foot at setup. Lean left (for a right-hander) so the club enters the sand in the same spot every time.',
    },
    {
      id: 'commit_ratio',
      label: 'Acceleration through strike',
      unit: '×',
      angle: 'any',
      phase: 'finish',
      benchmark: { min: 0.7, ideal: 1.0, max: 1.4 },
      description: 'Hand speed at the strike relative to peak downswing speed. Below ~0.7 means quitting into the sand — the cardinal bunker sin.',
      progressMetric: true,
    },
    {
      id: 'follow_length',
      label: 'Follow-through length',
      unit: '% backswing',
      angle: 'any',
      phase: 'finish',
      benchmark: { min: 70, ideal: 100, max: 140 },
      description: 'Follow-through size relative to the backswing. The finish should match or beat the backswing — sand steals speed.',
      progressMetric: true,
    },
    {
      id: 'tempo_ratio',
      label: 'Tempo ratio',
      unit: ':1',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 1.0, ideal: 1.6, max: 2.4 },
      description: 'Backswing time over downswing time for the splash.',
    },
  ],
  faults: [
    {
      tag: 'bunker-quit',
      name: 'Quitting in the sand',
      angle: 'any',
      phase: 'finish',
      detect: { metric: 'commit_ratio', when: 'below', value: 0.7 },
      description: 'Your hands decelerate into the strike. Sand kills clubhead speed, so any deceleration leaves the ball in the bunker.',
      tip: 'The sand is the shot — accelerate through it. Think "thump and turn" with the finish bigger than the backswing.',
      drill: 'Draw a line in the sand and splash it out with full finishes, no ball, ten times. Then put a ball just ahead of the line.',
      searchKeywords: ['accelerate through bunker shot', 'stop leaving ball in bunker', 'bunker commit drill', 'splash shot technique'],
    },
    {
      tag: 'bunker-short-follow',
      name: 'Follow-through too short',
      angle: 'any',
      phase: 'finish',
      detect: { metric: 'follow_length', when: 'below', value: 70 },
      description: 'Your follow-through is much shorter than your backswing — a stab at the sand rather than a swing through it.',
      tip: 'Match the finish to the backswing. Long back, long through — the sand does the distance control.',
      drill: 'Hold every bunker finish with hands at least shoulder height until the ball lands.',
      searchKeywords: ['bunker follow through drill', 'full finish bunker shot', 'greenside bunker basics'],
    },
    {
      tag: 'bunker-standing-up',
      name: 'Standing up through the strike',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'knee_flex_loss', when: 'above', value: 10 },
      description: 'Your legs straighten through the strike, raising the club\'s entry point — that\'s where bladed bunker shots come from.',
      tip: 'Keep the knees flexed and your height constant until the sand has been thrown.',
      drill: 'Rehearse splashes feeling your head stay at address height — a friend\'s hand hovering above your cap works.',
      searchKeywords: ['bladed bunker shots fix', 'stay down bunker shot', 'knee flex short game'],
    },
    {
      tag: 'bunker-narrow-stance',
      name: 'Stance too narrow',
      angle: 'face_on',
      phase: 'address',
      detect: { metric: 'stance_width', when: 'below', value: 1.1 },
      description: 'Your base is too narrow for sand. A narrow stance rides high in the sand and makes it hard to swing under the ball.',
      tip: 'Widen your feet beyond shoulder width and shuffle them into the sand until you feel planted.',
      drill: 'Set up, then jump lightly — if you wobble on landing, go wider until you don\'t.',
      searchKeywords: ['bunker setup basics', 'bunker stance width', 'greenside bunker setup'],
    },
    {
      tag: 'bunker-no-hinge',
      name: 'No early wrist set',
      angle: 'any',
      phase: 'top',
      detect: { metric: 'early_hinge', when: 'below', value: 5 },
      description: 'Your backswing is wide and shallow like a fairway swing. Splash shots need a steep, early hinge so the club can enter the sand close behind the ball.',
      tip: 'Set the wrists almost immediately — hands stay low, clubhead works up fast.',
      drill: 'Hinge-and-hold rehearsals: take the club back hinging fully by hip height, then splash the line.',
      searchKeywords: ['wrist hinge bunker shot', 'steep backswing sand', 'bunker technique wrist set'],
    },
    {
      tag: 'bunker-weight-back',
      name: 'Weight on the back foot',
      angle: 'face_on',
      phase: 'address',
      detect: { metric: 'weight_forward_address', when: 'below', value: 5 },
      description: 'Your setup favours the trail foot. In sand that moves the entry point behind the ball inconsistently — sometimes way behind it.',
      tip: 'Set 60–70% of your pressure into the lead foot and keep it there for the whole shot.',
      drill: 'Hit splash shots with your trail foot toe-down on its tip — all pressure lives on the lead side.',
      searchKeywords: ['bunker weight forward setup', 'lean left bunker shot', 'strike point bunker drill'],
    },
    {
      tag: 'bunker-head-movement',
      name: 'Unstable head through the shot',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'head_sway', when: 'above', value: 12 },
      description: 'Your head moves through the shot, which moves the club\'s entry point in the sand — the one thing a bunker shot cannot survive.',
      tip: 'Pick a grain of sand two inches behind the ball and keep your eyes on it until the sand flies.',
      drill: 'Splash lines in the sand with your feet quiet and head frozen; check every divot starts on the line.',
      searchKeywords: ['consistent bunker strike', 'head still short game', 'bunker entry point drill'],
    },
  ],
  recordingTips: {
    face_on: 'Camera chest-high outside the bunker, square to your chest, whole body in frame. Avoid shooting into low sun.',
    down_the_line: 'Camera behind the ball-target line at hand height, far enough back to keep the full swing in frame.',
  },
};

// ---------------------------------------------------------------------------
// CHIPPING — low-point control: weight left, hands lead, body turns, wrists quiet.
// ---------------------------------------------------------------------------

const CHIPPING = {
  id: 'chipping',
  label: 'Chipping',
  swingClass: 'short',
  summary:
    'Greenside chip. Analysis focuses on weight staying on the lead side, hands ahead of the ball, a body-driven stroke with quiet wrists, and matching stroke lengths.',
  phases: [
    { id: 'address', label: 'Address', description: 'Narrow stance, weight left, hands ahead.' },
    { id: 'top', label: 'Backswing End', description: 'Compact arm swing, minimal hinge.' },
    { id: 'impact', label: 'Impact', description: 'Hands still leading, ball then turf.' },
    { id: 'finish', label: 'Finish', description: 'Chest rotated through, club low and left.' },
  ],
  tempo: { idealRatio: 1.4, min: 0.9, max: 2.2, label: 'Backswing : downswing time. Chips are close to even-paced.' },
  metrics: [
    {
      id: 'stance_width',
      label: 'Stance width',
      unit: '× shoulders',
      angle: 'face_on',
      phase: 'address',
      benchmark: { min: 0.5, ideal: 0.75, max: 1.0 },
      description: 'Ankle spread relative to shoulder width — chipping wants a narrow base to encourage body turn.',
    },
    {
      id: 'weight_forward_address',
      label: 'Weight forward at address',
      unit: '% stance',
      angle: 'face_on',
      phase: 'address',
      benchmark: { min: 10, ideal: 25, max: 45 },
      description: 'Body centre favouring the lead foot at setup. Weight left presets a downward strike.',
      progressMetric: true,
    },
    {
      id: 'weight_forward_impact',
      label: 'Weight forward at impact',
      unit: '% stance',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 10, ideal: 28, max: 50 },
      description: 'Weight at the strike — it should stay left or move further left, never drift back.',
    },
    {
      id: 'hands_forward_impact',
      label: 'Hands ahead at impact',
      unit: '% torso',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 2, ideal: 10, max: 22 },
      description: '2D shaft-lean proxy at the strike. Hands leading keeps the loft stable and contact ball-first.',
      progressMetric: true,
    },
    {
      id: 'wrist_quietness',
      label: 'Wrist quietness',
      unit: '°',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0, ideal: 10, max: 25 },
      description: '2D proxy: how much the lead-arm/elbow geometry changes through the stroke. Big change = flicky wrists.',
      progressMetric: true,
    },
    {
      id: 'stroke_symmetry',
      label: 'Follow-through vs backswing',
      unit: '%',
      angle: 'any',
      phase: 'finish',
      benchmark: { min: 60, ideal: 90, max: 130 },
      description: 'Follow-through length relative to backswing. A jabby chip has a long backswing and no exit.',
    },
    {
      id: 'commit_ratio',
      label: 'Acceleration through impact',
      unit: '×',
      angle: 'any',
      phase: 'finish',
      benchmark: { min: 0.7, ideal: 0.95, max: 1.3 },
      description: 'Hand speed at impact relative to peak downswing speed — chips must not decelerate.',
    },
    {
      id: 'head_sway',
      label: 'Head movement',
      unit: '% torso',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 0, ideal: 3, max: 10 },
      description: 'Head drift through the chip. Low-point control needs a still centre.',
    },
    {
      id: 'chest_rotation_finish',
      label: 'Chest rotation at finish',
      unit: '°',
      angle: 'face_on',
      phase: 'finish',
      benchmark: { min: 15, ideal: 35, max: 60 },
      description: '2D proxy of how much the chest has turned toward the target at the finish. The body, not the hands, moves the club.',
    },
    {
      id: 'tempo_ratio',
      label: 'Tempo ratio',
      unit: ':1',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0.9, ideal: 1.4, max: 2.2 },
      description: 'Backswing time over downswing time.',
    },
  ],
  faults: [
    {
      tag: 'chipping-wristy',
      name: 'Wristy, flicky strike',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'wrist_quietness', when: 'above', value: 25 },
      description: 'Your wrists are doing the work through the ball. Flicking adds loft unpredictably and produces both duffs and thins from the same motion.',
      tip: 'Feel the triangle of arms and chest turn back and through together — the wrists stay passive.',
      drill: 'Chip with an alignment stick down the grip against your lead side — if the stick hits your ribs, the wrists flicked.',
      searchKeywords: ['stop flicking wrists chipping', 'chipping technique body rotation', 'quiet hands chipping drill', 'dan grieve chipping'],
    },
    {
      tag: 'chipping-weight-back',
      name: 'Weight falling back',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'weight_forward_impact', when: 'below', value: 10 },
      description: 'Your weight drifts to the trail foot through the chip — usually an instinct to "help" the ball up. The club then bottoms out behind the ball.',
      tip: 'Set weight left at address and keep it there. Trust the loft: the club lifts the ball, not you.',
      drill: 'Chip with your trail foot pulled back onto its toe, all pressure on the lead leg.',
      searchKeywords: ['weight forward chipping', 'stop duffing chips', 'chipping setup weight left'],
    },
    {
      tag: 'chipping-scoop',
      name: 'Scooping at impact',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'hands_forward_impact', when: 'below', value: 2 },
      description: 'Your hands are level with or behind the clubhead at the strike, adding loft and exposing the leading edge — the classic thin-chip position.',
      tip: 'Keep the hands leading the clubhead through the ball; the shaft should lean toward the target at the strike.',
      drill: 'Hit chips finishing with the club shaft pointing at your belt buckle — no wrist throw past the ball.',
      searchKeywords: ['stop scooping chips', 'hands ahead chipping drill', 'shaft lean chipping', 'crisp chip contact'],
    },
    {
      tag: 'chipping-decel',
      name: 'Decelerating into the ball',
      angle: 'any',
      phase: 'finish',
      detect: { metric: 'commit_ratio', when: 'below', value: 0.7 },
      description: 'Your stroke slows down into impact — the backswing was too long for the shot, so instinct hit the brakes.',
      tip: 'Shorter back, accelerating through. Distance comes from stroke length, never from easing off.',
      drill: 'Ladder drill: chip to 5, 10, 15 m targets changing only backswing length, always accelerating through.',
      searchKeywords: ['stop decelerating chipping', 'chipping distance control drill', 'short game acceleration'],
    },
    {
      tag: 'chipping-jab',
      name: 'Jabby stroke — no follow-through',
      angle: 'any',
      phase: 'finish',
      detect: { metric: 'stroke_symmetry', when: 'below', value: 60 },
      description: 'Your follow-through is much shorter than your backswing — a stab, not a stroke. Contact and spin become lottery numbers.',
      tip: 'Finish the chip: chest turns, club exits low and left, hold the finish for a beat.',
      drill: 'Brush-brush drill: continuous practice strokes brushing the grass through the same spot, then repeat with a ball.',
      searchKeywords: ['chipping follow through drill', 'smooth chipping stroke', 'stop stabbing at chips'],
    },
    {
      tag: 'chipping-no-body',
      name: 'All arms, no body turn',
      angle: 'face_on',
      phase: 'finish',
      detect: { metric: 'chest_rotation_finish', when: 'below', value: 15 },
      description: 'Your chest barely rotates through the chip, leaving the arms and hands to time everything on their own.',
      tip: 'Feel your sternum face the target at the finish — the arms just come along for the ride.',
      drill: 'Chip with the butt of the grip touching your belly button (long-grip drill); the body must turn to move the club.',
      searchKeywords: ['body rotation chipping', 'chest turn chip shot', 'connected chipping drill'],
    },
    {
      tag: 'chipping-wide-stance',
      name: 'Stance too wide',
      angle: 'face_on',
      phase: 'address',
      detect: { metric: 'stance_width', when: 'above', value: 1.0 },
      description: 'Your chipping stance is as wide as a full-swing stance, which blocks the small body turn a chip needs and invites sway.',
      tip: 'Feet inside shoulder width, lead foot dropped slightly back — a putting-like base.',
      drill: 'Set up with your heels one clubhead apart and hit ten chips; widen only until you feel stable.',
      searchKeywords: ['chipping setup basics', 'narrow stance chipping', 'chip shot setup'],
    },
    {
      tag: 'chipping-head-movement',
      name: 'Head moving through the chip',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'head_sway', when: 'above', value: 10 },
      description: 'Your head drifts during the stroke. Chips are precision strikes — a moving centre moves the low point.',
      tip: 'Watch the blade of grass under the ball until after the strike.',
      drill: 'Chip looking at the landing spot only after you hear the strike — never before.',
      searchKeywords: ['head still chipping', 'consistent chip strike drill', 'low point control chipping'],
    },
  ],
  recordingTips: {
    face_on: 'Camera waist-high, 2–3 m away, square to your chest. Ball, feet, and hands all in frame.',
    down_the_line: 'Camera waist-high on the ball-target line behind your hands, close enough to fill the frame with your body.',
  },
};

// ---------------------------------------------------------------------------
// PUTTING — pendulum: shoulders rock, wrists quiet, head and body frozen.
// ---------------------------------------------------------------------------

const PUTTING = {
  id: 'putting',
  label: 'Putting',
  swingClass: 'stroke',
  summary:
    'Putting stroke. Analysis focuses on a shoulder-driven pendulum, a frozen head and lower body, symmetric stroke lengths, and a repeatable ~2:1 tempo.',
  phases: [
    { id: 'address', label: 'Address', description: 'Eyes over the ball, light grip, still base.' },
    { id: 'top', label: 'Backstroke End', description: 'Furthest point of the backstroke.' },
    { id: 'impact', label: 'Impact', description: 'Putter returns to the ball.' },
    { id: 'finish', label: 'Finish', description: 'Stroke released and held toward the hole.' },
  ],
  tempo: { idealRatio: 2.0, min: 1.5, max: 2.6, label: 'Backstroke : through-stroke time. Great putters sit near 2:1.' },
  metrics: [
    {
      id: 'head_stillness',
      label: 'Head stillness',
      unit: '% torso',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0, ideal: 2, max: 6 },
      description: 'Total head movement from address to just after impact. The gold standard is zero — listen for the ball to drop.',
      progressMetric: true,
    },
    {
      id: 'body_sway',
      label: 'Lower-body stability',
      unit: '% torso',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0, ideal: 2, max: 7 },
      description: 'Hip movement during the stroke. The lower body is the tripod — it must not move.',
      progressMetric: true,
    },
    {
      id: 'wrist_quietness',
      label: 'Wrist quietness',
      unit: '°',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0, ideal: 5, max: 15 },
      description: '2D proxy of arm-geometry change through the stroke. A pendulum keeps the arms and putter as one unit; big change = handsy stroke.',
      progressMetric: true,
    },
    {
      id: 'pendulum_arc',
      label: 'Pendulum consistency',
      unit: '% torso',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0, ideal: 2, max: 6 },
      description: 'Variation in the distance between shoulders and hands during the stroke. A true shoulder pendulum keeps it constant.',
    },
    {
      id: 'stroke_symmetry',
      label: 'Through-stroke vs backstroke',
      unit: '%',
      angle: 'any',
      phase: 'finish',
      benchmark: { min: 80, ideal: 105, max: 140 },
      description: 'Through-stroke length relative to backstroke. Slightly longer through the ball is ideal; much shorter is a jab.',
      progressMetric: true,
    },
    {
      id: 'commit_ratio',
      label: 'Acceleration at impact',
      unit: '×',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 0.75, ideal: 1.0, max: 1.25 },
      description: 'Hand speed at impact relative to peak stroke speed — the putter should be coasting smoothly, not braking or lunging.',
    },
    {
      id: 'shoulder_engine',
      label: 'Shoulder-driven stroke',
      unit: '°',
      angle: 'face_on',
      phase: 'impact',
      benchmark: { min: 2, ideal: 6, max: 14 },
      description: '2D proxy: how much the shoulder line rocks during the stroke. Too little means the hands are the engine.',
    },
    {
      id: 'tempo_ratio',
      label: 'Tempo ratio',
      unit: ':1',
      angle: 'any',
      phase: 'impact',
      benchmark: { min: 1.5, ideal: 2.0, max: 2.6 },
      description: 'Backstroke time over through-stroke time. ~2:1 is the tour pattern.',
      progressMetric: true,
    },
  ],
  faults: [
    {
      tag: 'putting-peek',
      name: 'Head moving — peeking early',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'head_stillness', when: 'above', value: 6 },
      description: 'Your head moves during the stroke, almost always from looking up to follow the ball. Even small head motion opens or closes the face at impact.',
      tip: 'Keep your eyes on the spot where the ball was until you hear it rolling.',
      drill: 'Putt ten three-footers with your eyes closed after address — feel the stroke, listen for the drop.',
      searchKeywords: ['keep head still putting', 'stop looking up putting', 'head movement putting drill'],
    },
    {
      tag: 'putting-wristy',
      name: 'Wristy stroke',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'wrist_quietness', when: 'above', value: 15 },
      description: 'Your hands and wrists are driving the putter instead of the shoulders. A handsy stroke changes loft and face angle through impact and wrecks distance control.',
      tip: 'Feel the triangle of shoulders, arms, and hands rock as one piece — the putter is attached to your sternum.',
      drill: 'Trap an alignment stick between your lead wrist and the grip; putt without the stick leaving your forearm.',
      searchKeywords: ['wristy putting stroke fix', 'shoulder putting stroke drill', 'pendulum putting stroke'],
    },
    {
      tag: 'putting-body-sway',
      name: 'Lower body moving',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'body_sway', when: 'above', value: 7 },
      description: 'Your hips or legs move during the stroke. The stroke path then depends on timing the body back to centre — a variable you don\'t want on the greens.',
      tip: 'Set your weight evenly, soften the knees, and feel "concrete legs" from takeaway to finish.',
      drill: 'Putt with a ball trapped between your knees — any sway drops it.',
      searchKeywords: ['stable lower body putting', 'still body putting drill', 'putting setup stability'],
    },
    {
      tag: 'putting-jab',
      name: 'Jabby / decelerating stroke',
      angle: 'any',
      phase: 'finish',
      detect: { metric: 'stroke_symmetry', when: 'below', value: 80 },
      description: 'Your through-stroke is much shorter than your backstroke — the putter is braking at the ball. Distance control on longer putts will be poor.',
      tip: 'Think "short back, long through". The putter head should finish past the ball at least as far as it went back.',
      drill: 'Place a tee one backstroke-length ahead of the ball; every through-stroke must reach it.',
      searchKeywords: ['stop decelerating putts', 'smooth putting stroke drill', 'putting follow through length'],
    },
    {
      tag: 'putting-tempo',
      name: 'Inconsistent tempo',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'tempo_ratio', when: 'outside', range: [1.5, 2.6] },
      description: 'Your backstroke-to-throughstroke timing is away from the reliable ~2:1 pattern, which makes speed control feel like guesswork.',
      tip: 'Find a repeating count — "one, two" back, "three" through — and keep it identical on every length of putt.',
      drill: 'Putt to a metronome app at 76 bpm: back on beat one, strike on beat two, for twenty putts.',
      searchKeywords: ['putting tempo drill', 'putting rhythm metronome', '2 to 1 putting tempo'],
    },
    {
      tag: 'putting-handsy-arc',
      name: 'Arms breaking down (arc changing)',
      angle: 'any',
      phase: 'impact',
      detect: { metric: 'pendulum_arc', when: 'above', value: 6 },
      description: 'The distance between your shoulders and hands changes during the stroke — the pendulum is hinging mid-swing instead of staying one unit.',
      tip: 'Lock the elbows-to-grip triangle and let the shoulders do all the moving.',
      drill: 'Hold a second club across both elbows against your chest and stroke putts keeping it pinned.',
      searchKeywords: ['one piece putting stroke', 'putting triangle drill', 'arms and shoulders putting'],
    },
    {
      tag: 'putting-no-shoulders',
      name: 'Shoulders not engaged',
      angle: 'face_on',
      phase: 'impact',
      detect: { metric: 'shoulder_engine', when: 'below', value: 2 },
      description: 'Your shoulder line barely moves during the stroke — the putter is being moved by hands alone.',
      tip: 'Feel the lead shoulder work slightly down-and-up like a see-saw; the putter follows for free.',
      drill: 'Putt one-handed (lead hand only) focusing on the shoulder rocking the arm — then add the trail hand without adding its muscles.',
      searchKeywords: ['rock shoulders putting', 'shoulder driven putting stroke', 'putting stroke engine drill'],
    },
  ],
  recordingTips: {
    face_on: 'Camera knee-high, 2 m away, square to your chest. Ball, putter head, and eyes all in frame.',
    down_the_line: 'Camera knee-high directly behind the ball on the start line — this shows stroke path and face rotation best.',
  },
};

const SHOT_TYPES = {
  driving: DRIVING,
  iron: IRON,
  bunker: BUNKER,
  chipping: CHIPPING,
  putting: PUTTING,
};

function getShotType(id) {
  const def = SHOT_TYPES[id];
  if (!def) throw new Error(`Unknown shot type: ${id}`);
  return def;
}

/** Metric ids tracked on the dashboard trend charts for a shot type. */
function progressMetricIds(shotTypeId) {
  return getShotType(shotTypeId)
    .metrics.filter((m) => m.progressMetric)
    .map((m) => m.id);
}

module.exports = { SHOT_TYPE_IDS, SHOT_TYPES, getShotType, progressMetricIds };
