/**
 * Static 2026 season schedules for tour pages.
 * Sources: PGA Tour / Sky Sports (FedEx season), DP World Tour / Golf News Net & europeantour.com,
 * LIV Golf / Wikipedia 2026 LIV Golf League, Korn Ferry Tour / PGA TOUR media release (Nov 2025),
 * LPGA Tour / Golf.com & LPGA 2026 schedule (33 events; majors: Chevron, U.S. Women’s Open, KPMG, Evian, AIG).
 * Men’s majors use app/session first-round dates: Masters 9 Apr, PGA 14 May, US Open 18 Jun, Open 16 Jul.
 */

import { withEventLinkFields } from './tourEventLinks';

export type TourSeasonEvent = {
  id: string;
  /** Two short lines for the timeline chip (e.g. THE / MASTERS). */
  shortName: readonly [string, string];
  fullName: string;
  /** Calendar date of first competitive round, YYYY-MM-DD. */
  startDate: string;
  /** Calendar date of final competitive round, YYYY-MM-DD (defaults to start + 3 days). */
  endDate?: string;
  isMajor: boolean;
  /** Site-specific path segment for leaderboard/results URLs. */
  slug?: string;
  /** PGA Tour perm number (3 digits), used with slug for pgatour.com links. */
  tournId?: string;
};

export type MajorChampionship = TourSeasonEvent & {
  /** Label inside the home timeline circle (e.g. Masters, US Open). */
  circleLabel: string;
  /** Direct leaderboard URL for the major's own site. */
  leaderboardUrl: string;
};

/** Men's majors — single source of truth for the home upcoming-events strip. */
export const MAJOR_CHAMPIONSHIPS: MajorChampionship[] = [
  {
    id: 'major-2026-masters',
    shortName: ['THE', 'MASTERS'],
    fullName: 'The Masters',
    startDate: '2026-04-09',
    endDate: '2026-04-12',
    isMajor: true,
    circleLabel: 'Masters',
    leaderboardUrl: 'https://www.masters.com/leaderboard',
  },
  {
    id: 'major-2026-pga-championship',
    shortName: ['PGA', 'CHAMP.'],
    fullName: 'PGA Championship',
    startDate: '2026-05-14',
    endDate: '2026-05-17',
    isMajor: true,
    circleLabel: 'PGA Champ',
    leaderboardUrl: 'https://www.pgachampionship.com/leaderboard',
  },
  {
    id: 'major-2026-us-open',
    shortName: ['U.S.', 'OPEN'],
    fullName: 'U.S. Open',
    startDate: '2026-06-18',
    endDate: '2026-06-21',
    isMajor: true,
    circleLabel: 'US Open',
    leaderboardUrl: 'https://www.usopen.com/2026/scoring.html',
  },
  {
    id: 'major-2026-the-open',
    shortName: ['THE', 'OPEN'],
    fullName: 'The Open Championship',
    startDate: '2026-07-16',
    endDate: '2026-07-19',
    isMajor: true,
    circleLabel: 'The Open',
    leaderboardUrl:
      'https://www.pgatour.com/tournaments/2026/the-open-championship/R2026100/past-results',
  },
];

/** Tour schedules that duplicate men's majors — exclude isMajor rows from merge. */
const TOUR_TITLES_EXCLUDING_MAJORS = new Set(['PGA Tour', 'DP World Tour']);

const PGA_TOUR_2026_FULL_SEASON: TourSeasonEvent[] = [
  {
    id: "pga-2026-sony-open-in-hawaii",
    shortName: ["SONY", "OPEN"],
    fullName: "Sony Open in Hawaii",
    startDate: "2026-01-15",
    isMajor: false,
  },
  {
    id: "pga-2026-the-american-express",
    shortName: ["AMERICAN", "EXPRESS"],
    fullName: "The American Express",
    startDate: "2026-01-22",
    isMajor: false,
  },
  {
    id: "pga-2026-farmers-insurance-open",
    shortName: ["FARMERS", "OPEN"],
    fullName: "Farmers Insurance Open",
    startDate: "2026-01-29",
    isMajor: false,
  },
  {
    id: "pga-2026-wm-phoenix-open",
    shortName: ["WM", "PHOENIX"],
    fullName: "WM Phoenix Open",
    startDate: "2026-02-05",
    isMajor: false,
  },
  {
    id: "pga-2026-att-pebble-beach-pro-am",
    shortName: ["AT&T", "PEBBLE"],
    fullName: "AT&T Pebble Beach Pro-Am",
    startDate: "2026-02-12",
    isMajor: false,
  },
  {
    id: "pga-2026-the-genesis-invitational",
    shortName: ["GENESIS", "INVIT."],
    fullName: "The Genesis Invitational",
    startDate: "2026-02-19",
    isMajor: false,
  },
  {
    id: "pga-2026-cognizant-classic",
    shortName: ["COGNI", "ZANT"],
    fullName: "Cognizant Classic",
    startDate: "2026-02-26",
    isMajor: false,
  },
  {
    id: "pga-2026-arnold-palmer-invitational",
    shortName: ["ARNOLD", "PALMER"],
    fullName: "Arnold Palmer Invitational presented by Mastercard",
    startDate: "2026-03-05",
    isMajor: false,
  },
  {
    id: "pga-2026-puerto-rico-open",
    shortName: ["PUERTO", "RICO"],
    fullName: "Puerto Rico Open",
    startDate: "2026-03-05",
    isMajor: false,
  },
  {
    id: "pga-2026-the-players",
    shortName: ["THE", "PLAYERS"],
    fullName: "THE PLAYERS Championship",
    startDate: "2026-03-12",
    isMajor: false,
  },
  {
    id: "pga-2026-valspar-championship",
    shortName: ["VALSPAR", "CHAMP."],
    fullName: "Valspar Championship",
    startDate: "2026-03-19",
    isMajor: false,
  },
  {
    id: "pga-2026-texas-childrens-houston-open",
    shortName: ["TEXAS", "CHILD."],
    fullName: "Texas Children's Houston Open",
    startDate: "2026-03-26",
    isMajor: false,
  },
  {
    id: "pga-2026-valero-texas-open",
    shortName: ["VALERO", "TEXAS"],
    fullName: "Valero Texas Open",
    startDate: "2026-04-02",
    isMajor: false,
  },
  {
    id: "pga-2026-masters",
    shortName: ["THE", "MASTERS"],
    fullName: "The Masters",
    startDate: "2026-04-09",
    isMajor: true,
  },
  {
    id: "pga-2026-rbc-heritage",
    shortName: ["RBC", "HERIT."],
    fullName: "RBC Heritage",
    startDate: "2026-04-16",
    isMajor: false,
  },
  {
    id: "pga-2026-zurich-classic",
    shortName: ["ZURICH", "CLASSIC"],
    fullName: "Zurich Classic of New Orleans",
    startDate: "2026-04-23",
    isMajor: false,
  },
  {
    id: "pga-2026-cadillac-championship",
    shortName: ["CADILLAC", "CHAMP."],
    fullName: "Cadillac Championship",
    startDate: "2026-04-30",
    isMajor: false,
  },
  {
    id: "pga-2026-truist-championship",
    shortName: ["TRUIST", "CHAMP."],
    fullName: "Truist Championship",
    startDate: "2026-05-07",
    isMajor: false,
  },
  {
    id: "pga-2026-myrtle-beach-classic",
    shortName: ["MYRTLE", "BEACH"],
    fullName: "ONEflight Myrtle Beach Classic",
    startDate: "2026-05-07",
    isMajor: false,
  },
  {
    id: "pga-2026-pga-championship",
    shortName: ["PGA", "CHAMP."],
    fullName: "PGA Championship",
    startDate: "2026-05-14",
    isMajor: true,
  },
  {
    id: "pga-2026-cj-cup-byron-nelson",
    shortName: ["CJ CUP", "BYRON"],
    fullName: "THE CJ CUP Byron Nelson",
    startDate: "2026-05-21",
    isMajor: false,
  },
  {
    id: "pga-2026-charles-schwab-challenge",
    shortName: ["CHARLES", "SCHWAB"],
    fullName: "Charles Schwab Challenge",
    startDate: "2026-05-28",
    isMajor: false,
  },
  {
    id: "pga-2026-memorial",
    shortName: ["THE", "MEMORIAL"],
    fullName: "the Memorial Tournament presented by Workday",
    startDate: "2026-06-04",
    isMajor: false,
  },
  {
    id: "pga-2026-rbc-canadian-open",
    shortName: ["RBC", "CANADA"],
    fullName: "RBC Canadian Open",
    startDate: "2026-06-11",
    isMajor: false,
  },
  {
    id: "pga-2026-us-open",
    shortName: ["U.S.", "OPEN"],
    fullName: "U.S. Open",
    startDate: "2026-06-18",
    isMajor: true,
  },
  {
    id: "pga-2026-travelers-championship",
    shortName: ["TRAVEL", "ERS"],
    fullName: "Travelers Championship",
    startDate: "2026-06-25",
    isMajor: false,
  },
  {
    id: "pga-2026-john-deere-classic",
    shortName: ["JOHN", "DEERE"],
    fullName: "John Deere Classic",
    startDate: "2026-07-02",
    isMajor: false,
  },
  {
    id: "pga-2026-genesis-scottish-open",
    shortName: ["GENESIS", "SCOT."],
    fullName: "Genesis Scottish Open",
    startDate: "2026-07-09",
    isMajor: false,
  },
  {
    id: "pga-2026-isco-championship",
    shortName: ["ISCO", "CHAMP."],
    fullName: "ISCO Championship",
    startDate: "2026-07-09",
    isMajor: false,
  },
  {
    id: "pga-2026-the-open",
    shortName: ["THE", "OPEN"],
    fullName: "The Open Championship",
    startDate: "2026-07-16",
    isMajor: true,
  },
  {
    id: "pga-2026-corales-puntacana",
    shortName: ["CORALES", "PUNTA"],
    fullName: "Corales Puntacana Championship",
    startDate: "2026-07-16",
    isMajor: false,
  },
  {
    id: "pga-2026-3m-open",
    shortName: ["3M", "OPEN"],
    fullName: "3M Open",
    startDate: "2026-07-23",
    isMajor: false,
  },
  {
    id: "pga-2026-rocket-classic",
    shortName: ["ROCKET", "DETROIT"],
    fullName: "Rocket Classic",
    startDate: "2026-07-30",
    isMajor: false,
  },
  {
    id: "pga-2026-wyndham-championship",
    shortName: ["WYNDHAM", "CHAMP."],
    fullName: "Wyndham Championship",
    startDate: "2026-08-06",
    isMajor: false,
  },
  {
    id: "pga-2026-fedex-st-jude",
    shortName: ["FEDEX", "ST JUDE"],
    fullName: "FedEx St. Jude Championship",
    startDate: "2026-08-13",
    isMajor: false,
  },
  {
    id: "pga-2026-bmw-championship",
    shortName: ["BMW", "CHAMP."],
    fullName: "BMW Championship",
    startDate: "2026-08-20",
    isMajor: false,
  },
  {
    id: "pga-2026-tour-championship",
    shortName: ["TOUR", "CHAMP."],
    fullName: "Tour Championship",
    startDate: "2026-08-27",
    isMajor: false,
  },
];

const DP_WORLD_TOUR_2026: TourSeasonEvent[] = [
  {
    id: "dpwt-2026-australian-pga",
    shortName: ["BMW", "AUS PGA"],
    fullName: "BMW Australian PGA Championship",
    startDate: "2025-11-27",
    isMajor: false,
  },
  {
    id: "dpwt-2026-australian-open",
    shortName: ["ISPS", "AUS OP"],
    fullName: "ISPS Handa Australian Open",
    startDate: "2025-12-04",
    isMajor: false,
  },
  {
    id: "dpwt-2026-nedbank",
    shortName: ["NED", "BANK"],
    fullName: "Nedbank Golf Challenge",
    startDate: "2025-12-04",
    isMajor: false,
  },
  {
    id: "dpwt-2026-dunhill-championship",
    shortName: ["ALFRED", "DUNHILL"],
    fullName: "Alfred Dunhill Championship",
    startDate: "2025-12-11",
    isMajor: false,
  },
  {
    id: "dpwt-2026-mauritius-open",
    shortName: ["AFRASIA", "MAUR."],
    fullName: "AfrAsia Bank Mauritius Open",
    startDate: "2025-12-18",
    isMajor: false,
  },
  {
    id: "dpwt-2026-dubai-invitational",
    shortName: ["DUBAI", "INVIT."],
    fullName: "Dubai Invitational",
    startDate: "2026-01-15",
    isMajor: false,
  },
  {
    id: "dpwt-2026-hero-dubai-desert",
    shortName: ["HERO", "DUBAI"],
    fullName: "Hero Dubai Desert Classic",
    startDate: "2026-01-22",
    isMajor: false,
  },
  {
    id: "dpwt-2026-bahrain-championship",
    shortName: ["BAHRAIN", "CHAMP."],
    fullName: "Bahrain Championship",
    startDate: "2026-01-28",
    isMajor: false,
  },
  {
    id: "dpwt-2026-qatar-masters",
    shortName: ["QATAR", "MAST."],
    fullName: "Qatar Masters",
    startDate: "2026-02-05",
    isMajor: false,
  },
  {
    id: "dpwt-2026-kenya-open",
    shortName: ["MAGICAL", "KENYA"],
    fullName: "Magical Kenya Open",
    startDate: "2026-02-19",
    isMajor: false,
  },
  {
    id: "dpwt-2026-sa-open",
    shortName: ["INVESTEC", "SA OP"],
    fullName: "Investec South African Open Championship",
    startDate: "2026-02-26",
    isMajor: false,
  },
  {
    id: "dpwt-2026-joburg-open",
    shortName: ["JOBURG", "OPEN"],
    fullName: "Joburg Open",
    startDate: "2026-03-05",
    isMajor: false,
  },
  {
    id: "dpwt-2026-hainan-classic",
    shortName: ["HAINAN", "CLASSIC"],
    fullName: "Hainan Classic",
    startDate: "2026-03-19",
    isMajor: false,
  },
  {
    id: "dpwt-2026-hero-indian-open",
    shortName: ["HERO", "INDIA"],
    fullName: "Hero Indian Open",
    startDate: "2026-03-26",
    isMajor: false,
  },
  {
    id: "dpwt-2026-masters",
    shortName: ["THE", "MASTERS"],
    fullName: "The Masters",
    startDate: "2026-04-09",
    isMajor: true,
  },
  {
    id: "dpwt-2026-volvo-china-open",
    shortName: ["VOLVO", "CHINA"],
    fullName: "Volvo China Open",
    startDate: "2026-04-23",
    isMajor: false,
  },
  {
    id: "dpwt-2026-turkish-airlines-open",
    shortName: ["TURKISH", "OPEN"],
    fullName: "Turkish Airlines Open",
    startDate: "2026-04-30",
    isMajor: false,
  },
  {
    id: "dpwt-2026-catalunya-championship",
    shortName: ["ESTRELLA", "CATAL."],
    fullName: "Estrella Damm Catalunya Championship",
    startDate: "2026-05-07",
    isMajor: false,
  },
  {
    id: "dpwt-2026-pga-championship",
    shortName: ["PGA", "CHAMP."],
    fullName: "PGA Championship",
    startDate: "2026-05-14",
    isMajor: true,
  },
  {
    id: "dpwt-2026-soudal-open",
    shortName: ["SOUDAL", "OPEN"],
    fullName: "Soudal Open",
    startDate: "2026-05-21",
    isMajor: false,
  },
  {
    id: "dpwt-2026-austrian-alpine-open",
    shortName: ["AUSTRIAN", "ALPINE"],
    fullName: "Austrian Alpine Open presented by Kitzbühel Tirol",
    startDate: "2026-05-28",
    isMajor: false,
  },
  {
    id: "dpwt-2026-klm-open",
    shortName: ["KLM", "OPEN"],
    fullName: "KLM Open",
    startDate: "2026-06-04",
    isMajor: false,
  },
  {
    id: "dpwt-2026-us-open",
    shortName: ["U.S.", "OPEN"],
    fullName: "U.S. Open",
    startDate: "2026-06-18",
    isMajor: true,
  },
  {
    id: "dpwt-2026-italian-open",
    shortName: ["ITALIAN", "OPEN"],
    fullName: "Italian Open",
    startDate: "2026-06-25",
    isMajor: false,
  },
  {
    id: "dpwt-2026-bmw-intl-open",
    shortName: ["BMW", "INTL."],
    fullName: "BMW International Open",
    startDate: "2026-07-02",
    isMajor: false,
  },
  {
    id: "dpwt-2026-genesis-scottish-open",
    shortName: ["GENESIS", "SCOT."],
    fullName: "Genesis Scottish Open",
    startDate: "2026-07-09",
    isMajor: false,
  },
  {
    id: "dpwt-2026-isco-championship",
    shortName: ["ISCO", "CHAMP."],
    fullName: "ISCO Championship",
    startDate: "2026-07-09",
    isMajor: false,
  },
  {
    id: "dpwt-2026-the-open",
    shortName: ["THE", "OPEN"],
    fullName: "The Open Championship",
    startDate: "2026-07-16",
    isMajor: true,
  },
  {
    id: "dpwt-2026-corales-puntacana",
    shortName: ["CORALES", "PUNTA"],
    fullName: "Corales Puntacana Championship",
    startDate: "2026-07-16",
    isMajor: false,
  },
  {
    id: "dpwt-2026-danish-championship",
    shortName: ["DANISH", "CHAMP."],
    fullName: "Danish Golf Championship",
    startDate: "2026-08-13",
    isMajor: false,
  },
  {
    id: "dpwt-2026-european-event-tba",
    shortName: ["EUROPEAN", "TBA"],
    fullName: "European Event (TBA)",
    startDate: "2026-08-20",
    isMajor: false,
  },
  {
    id: "dpwt-2026-british-masters",
    shortName: ["BRITISH", "MAST."],
    fullName: "Husqvarna British Masters hosted by Sir Nick Faldo",
    startDate: "2026-08-27",
    isMajor: false,
  },
  {
    id: "dpwt-2026-omega-european-masters",
    shortName: ["OMEGA", "EU MAS"],
    fullName: "Omega European Masters",
    startDate: "2026-09-03",
    isMajor: false,
  },
  {
    id: "dpwt-2026-irish-open",
    shortName: ["AMGEN", "IRISH"],
    fullName: "Amgen Irish Open",
    startDate: "2026-09-10",
    isMajor: false,
  },
  {
    id: "dpwt-2026-bmw-pga",
    shortName: ["BMW", "PGA"],
    fullName: "BMW PGA Championship",
    startDate: "2026-09-17",
    isMajor: false,
  },
  {
    id: "dpwt-2026-open-de-france",
    shortName: ["FEDEX", "FRANCE"],
    fullName: "FedEx Open de France",
    startDate: "2026-09-24",
    isMajor: false,
  },
  {
    id: "dpwt-2026-dunhill-links",
    shortName: ["DUNHILL", "LINKS"],
    fullName: "Alfred Dunhill Links Championship",
    startDate: "2026-10-01",
    isMajor: false,
  },
  {
    id: "dpwt-2026-open-espana",
    shortName: ["OPEN", "ESPAÑA"],
    fullName: "Open de España presented by Madrid",
    startDate: "2026-10-09",
    isMajor: false,
  },
  {
    id: "dpwt-2026-india-championship",
    shortName: ["DP WORLD", "INDIA"],
    fullName: "DP World India Championship",
    startDate: "2026-10-15",
    isMajor: false,
  },
  {
    id: "dpwt-2026-genesis-championship",
    shortName: ["GENESIS", "CHAMP."],
    fullName: "Genesis Championship",
    startDate: "2026-10-22",
    isMajor: false,
  },
  {
    id: "dpwt-2026-abu-dhabi-championship",
    shortName: ["ABU", "DHABI"],
    fullName: "Abu Dhabi Championship",
    startDate: "2026-11-05",
    isMajor: false,
  },
  {
    id: "dpwt-2026-tour-championship-dubai",
    shortName: ["DPWTC", "DUBAI"],
    fullName: "DP World Tour Championship, Dubai",
    startDate: "2026-11-12",
    isMajor: false,
  },
];

const LIV_GOLF_2026: TourSeasonEvent[] = [
  {
    id: "liv-2026-riyadh",
    shortName: ["LIV", "RIYADH"],
    fullName: "LIV Golf Riyadh",
    startDate: "2026-02-07",
    isMajor: false,
  },
  {
    id: "liv-2026-adelaide",
    shortName: ["LIV", "ADELAIDE"],
    fullName: "LIV Golf Adelaide",
    startDate: "2026-02-15",
    isMajor: false,
  },
  {
    id: "liv-2026-hong-kong",
    shortName: ["LIV", "HK"],
    fullName: "LIV Golf Hong Kong",
    startDate: "2026-03-08",
    isMajor: false,
  },
  {
    id: "liv-2026-singapore",
    shortName: ["LIV", "SING."],
    fullName: "LIV Golf Singapore",
    startDate: "2026-03-15",
    isMajor: false,
  },
  {
    id: "liv-2026-south-africa",
    shortName: ["LIV", "S.AFR."],
    fullName: "LIV Golf South Africa",
    startDate: "2026-03-22",
    isMajor: false,
  },
  {
    id: "liv-2026-mexico-city",
    shortName: ["LIV", "MEXICO"],
    fullName: "LIV Golf Mexico City",
    startDate: "2026-04-19",
    isMajor: false,
  },
  {
    id: "liv-2026-virginia",
    shortName: ["LIV", "VA"],
    fullName: "LIV Golf Virginia",
    startDate: "2026-05-10",
    isMajor: false,
  },
  {
    id: "liv-2026-korea",
    shortName: ["LIV", "KOREA"],
    fullName: "LIV Golf Korea",
    startDate: "2026-05-31",
    isMajor: false,
  },
  {
    id: "liv-2026-andalucia",
    shortName: ["LIV", "ANDAL."],
    fullName: "LIV Golf Andalucía",
    startDate: "2026-06-07",
    isMajor: false,
  },
  {
    id: "liv-2026-louisiana",
    shortName: ["LIV", "LA"],
    fullName: "LIV Golf Louisiana",
    startDate: "2026-06-28",
    isMajor: false,
  },
  {
    id: "liv-2026-uk",
    shortName: ["LIV", "U.K."],
    fullName: "LIV Golf UK",
    startDate: "2026-07-26",
    isMajor: false,
  },
  {
    id: "liv-2026-new-york",
    shortName: ["LIV", "NYC"],
    fullName: "LIV Golf New York",
    startDate: "2026-08-09",
    isMajor: false,
  },
  {
    id: "liv-2026-indianapolis",
    shortName: ["LIV", "INDY"],
    fullName: "LIV Golf Indianapolis",
    startDate: "2026-08-23",
    isMajor: false,
  },
  {
    id: "liv-2026-team-championship",
    shortName: ["LIV", "TEAMS"],
    fullName: "LIV Golf Team Championship",
    startDate: "2026-08-30",
    isMajor: false,
  },
];

const KORN_FERRY_TOUR_2026: TourSeasonEvent[] = [
  {
    id: "kft-2026-bahamas-atlantis",
    shortName: ["BAHA", "ATLANTIS"],
    fullName: "The Bahamas Golf Classic at Atlantis Paradise Island",
    startDate: "2026-01-08",
    isMajor: false,
  },
  {
    id: "kft-2026-bahamas-abaco",
    shortName: ["BAHA", "ABACO"],
    fullName: "The Bahamas Great Abaco Classic at The Abaco Club",
    startDate: "2026-01-15",
    isMajor: false,
  },
  {
    id: "kft-2026-panama",
    shortName: ["PANAMA", "CHAMP."],
    fullName: "The Panama Championship",
    startDate: "2026-01-29",
    isMajor: false,
  },
  {
    id: "kft-2026-astara-bogota",
    shortName: ["ASTARA", "BOGOTÁ"],
    fullName: "Astara Golf Championship presented by Mastercard",
    startDate: "2026-02-05",
    isMajor: false,
  },
  {
    id: "kft-2026-argentina-open",
    shortName: ["VISA", "ARG."],
    fullName: "119 Visa Argentina Open presented by Macro",
    startDate: "2026-02-26",
    isMajor: false,
  },
  {
    id: "kft-2026-astara-chile",
    shortName: ["ASTARA", "CHILE"],
    fullName: "Astara Chile Classic presented by Scotiabank",
    startDate: "2026-03-05",
    isMajor: false,
  },
  {
    id: "kft-2026-club-car-the-landings",
    shortName: ["CLUB", "CAR"],
    fullName: "Club Car Championship at The Landings Golf & Athletic Club",
    startDate: "2026-03-26",
    isMajor: false,
  },
  {
    id: "kft-2026-lecom-suncoast",
    shortName: ["LECOM", "SUNCOAST"],
    fullName: "LECOM Suncoast Classic",
    startDate: "2026-04-02",
    isMajor: false,
  },
  {
    id: "kft-2026-tulum",
    shortName: ["TULUM", "RIVIERA"],
    fullName: "Tulum Championship at PGA Riviera Maya",
    startDate: "2026-04-16",
    isMajor: false,
  },
  {
    id: "kft-2026-colonial-life-charity",
    shortName: ["COLONIAL", "LIFE"],
    fullName: "Colonial Life Charity Classic",
    startDate: "2026-05-14",
    isMajor: false,
  },
  {
    id: "kft-2026-visit-knoxville",
    shortName: ["KNOX", "VILLE"],
    fullName: "Visit Knoxville Open",
    startDate: "2026-05-21",
    isMajor: false,
  },
  {
    id: "kft-2026-unc-health",
    shortName: ["UNC", "HLTH."],
    fullName: "UNC Health Championship",
    startDate: "2026-05-28",
    isMajor: false,
  },
  {
    id: "kft-2026-bmw-charity-pro-am",
    shortName: ["BMW", "CHARITY"],
    fullName: "BMW Charity Pro-Am presented by TD SYNNEX",
    startDate: "2026-06-04",
    isMajor: false,
  },
  {
    id: "kft-2026-occunet-amarillo",
    shortName: ["OCCUNET", "TX"],
    fullName: "OccuNet Classic presented by Amarillo National Bank",
    startDate: "2026-06-11",
    isMajor: false,
  },
  {
    id: "kft-2026-memorial-health",
    shortName: ["MEM.", "HLTH."],
    fullName: "Memorial Health Championship presented by LRS",
    startDate: "2026-06-25",
    isMajor: false,
  },
  {
    id: "kft-2026-blue-championship",
    shortName: ["BLUE", "CHAMP."],
    fullName: "The Blue Championship",
    startDate: "2026-07-09",
    isMajor: false,
  },
  {
    id: "kft-2026-nv5-invitational",
    shortName: ["NV5", "INVIT."],
    fullName: "NV5 Invitational",
    startDate: "2026-07-23",
    isMajor: false,
  },
  {
    id: "kft-2026-utah-championship",
    shortName: ["UTAH", "CHAMP."],
    fullName: "Utah Championship presented by Zions Bank and Intermountain Health",
    startDate: "2026-07-30",
    isMajor: false,
  },
  {
    id: "kft-2026-pinnacle-bank",
    shortName: ["PINNACLE", "BANK"],
    fullName: "Pinnacle Bank Championship presented by Woodhouse",
    startDate: "2026-08-06",
    isMajor: false,
  },
  {
    id: "kft-2026-albertsons-boise",
    shortName: ["ALBER", "TSONS"],
    fullName: "Albertsons Boise Open presented by Chevron",
    startDate: "2026-08-13",
    isMajor: false,
  },
  {
    id: "kft-2026-adventhealth",
    shortName: ["ADVENT", "HLTH."],
    fullName: "AdventHealth Championship",
    startDate: "2026-08-20",
    isMajor: false,
  },
  {
    id: "kft-2026-simmons-bank-open",
    shortName: ["SIMMONS", "BANK"],
    fullName: "Simmons Bank Open for the Snedeker Foundation",
    startDate: "2026-09-10",
    isMajor: false,
  },
  {
    id: "kft-2026-nationwide-childrens",
    shortName: ["NATION", "WIDE"],
    fullName: "Nationwide Children's Hospital Championship",
    startDate: "2026-09-17",
    isMajor: false,
  },
  {
    id: "kft-2026-compliance-solutions",
    shortName: ["COMPL.", "SOL."],
    fullName: "Compliance Solutions Championship",
    startDate: "2026-10-01",
    isMajor: false,
  },
  {
    id: "kft-2026-tour-championship-richmond",
    shortName: ["KFT", "FINALE"],
    fullName: "Korn Ferry Tour Championship presented by Virginia's Richmond Region",
    startDate: "2026-10-08",
    isMajor: false,
  },
];

/** 33 events; first-round dates from LPGA / Golf.com 2026 schedule. */
const LPGA_TOUR_2026: TourSeasonEvent[] = [
  {
    id: "lpga-2026-hilton-grand-vacations-toc",
    shortName: ["HILTON", "TOC"],
    fullName: "Hilton Grand Vacations Tournament of Champions",
    startDate: "2026-01-29",
    isMajor: false,
  },
  {
    id: "lpga-2026-honda-lpga-thailand",
    shortName: ["HONDA", "THAI."],
    fullName: "Honda LPGA Thailand",
    startDate: "2026-02-19",
    isMajor: false,
  },
  {
    id: "lpga-2026-hsbc-womens-world",
    shortName: ["HSBC", "WORLD"],
    fullName: "HSBC Women’s World Championship",
    startDate: "2026-02-26",
    isMajor: false,
  },
  {
    id: "lpga-2026-blue-bay-lpga",
    shortName: ["BLUE", "BAY"],
    fullName: "Blue Bay LPGA",
    startDate: "2026-03-05",
    isMajor: false,
  },
  {
    id: "lpga-2026-fortinet-founders-cup",
    shortName: ["FORTI", "FOUND."],
    fullName: "Fortinet Founders Cup",
    startDate: "2026-03-19",
    isMajor: false,
  },
  {
    id: "lpga-2026-ford-championship",
    shortName: ["FORD", "CHAMP."],
    fullName: "Ford Championship presented by Wild Horse Pass",
    startDate: "2026-03-26",
    isMajor: false,
  },
  {
    id: "lpga-2026-aramco-championship",
    shortName: ["ARAMCO", "CHAMP."],
    fullName: "Aramco Championship",
    startDate: "2026-04-02",
    isMajor: false,
  },
  {
    id: "lpga-2026-jm-eagle-la-championship",
    shortName: ["JM", "LA CH."],
    fullName: "JM Eagle LA Championship presented by Plastpro",
    startDate: "2026-04-16",
    isMajor: false,
  },
  {
    id: "lpga-2026-chevron-championship",
    shortName: ["CHEVRON", "CHAMP."],
    fullName: "Chevron Championship",
    startDate: "2026-04-23",
    isMajor: true,
  },
  {
    id: "lpga-2026-mexico-riviera-maya",
    shortName: ["MEXICO", "MAYAK."],
    fullName: "Mexico Riviera Maya Open at Mayakoba",
    startDate: "2026-04-30",
    isMajor: false,
  },
  {
    id: "lpga-2026-mizuho-americas-open",
    shortName: ["MIZUHO", "OPEN"],
    fullName: "Mizuho Americas Open",
    startDate: "2026-05-07",
    isMajor: false,
  },
  {
    id: "lpga-2026-kroger-queen-city",
    shortName: ["KROGER", "QUEEN"],
    fullName: "Kroger Queen City Championship",
    startDate: "2026-05-14",
    isMajor: false,
  },
  {
    id: "lpga-2026-shoprite-lpga",
    shortName: ["SHOP", "RITE"],
    fullName: "ShopRite LPGA Classic presented by Wakefern",
    startDate: "2026-05-28",
    isMajor: false,
  },
  {
    id: "lpga-2026-us-womens-open",
    shortName: ["U.S.", "W. OPEN"],
    fullName: "U.S. Women’s Open presented by Ally",
    startDate: "2026-06-04",
    isMajor: true,
  },
  {
    id: "lpga-2026-dow-championship",
    shortName: ["DOW", "CHAMP."],
    fullName: "Dow Championship",
    startDate: "2026-06-11",
    isMajor: false,
  },
  {
    id: "lpga-2026-meijer-lpga-classic",
    shortName: ["MEIJER", "LPGA"],
    fullName: "Meijer LPGA Classic for Simply Give",
    startDate: "2026-06-18",
    isMajor: false,
  },
  {
    id: "lpga-2026-kpmg-womens-pga",
    shortName: ["KPMG", "W PGA"],
    fullName: "KPMG Women’s PGA Championship",
    startDate: "2026-06-25",
    isMajor: true,
  },
  {
    id: "lpga-2026-amundi-evian",
    shortName: ["AMUNDI", "EVIAN"],
    fullName: "The Amundi Evian Championship",
    startDate: "2026-07-09",
    isMajor: true,
  },
  {
    id: "lpga-2026-womens-scottish-open",
    shortName: ["ISPS", "SCOT."],
    fullName: "ISPS HANDA Women’s Scottish Open",
    startDate: "2026-07-23",
    isMajor: false,
  },
  {
    id: "lpga-2026-aig-womens-open",
    shortName: ["AIG", "W OPEN"],
    fullName: "AIG Women’s Open",
    startDate: "2026-07-30",
    isMajor: true,
  },
  {
    id: "lpga-2026-portland-classic",
    shortName: ["PORT", "LAND"],
    fullName: "The Standard Portland Classic",
    startDate: "2026-08-13",
    isMajor: false,
  },
  {
    id: "lpga-2026-cpkc-womens-open",
    shortName: ["CPKC", "OPEN"],
    fullName: "CPKC Women’s Open",
    startDate: "2026-08-20",
    isMajor: false,
  },
  {
    id: "lpga-2026-fm-championship",
    shortName: ["FM", "CHAMP."],
    fullName: "FM Championship",
    startDate: "2026-08-27",
    isMajor: false,
  },
  {
    id: "lpga-2026-solheim-cup",
    shortName: ["SOL", "HEIM"],
    fullName: "Solheim Cup",
    startDate: "2026-09-11",
    isMajor: false,
  },
  {
    id: "lpga-2026-walmart-nw-arkansas",
    shortName: ["WAL", "MART"],
    fullName: "Walmart NW Arkansas Championship presented by P&G",
    startDate: "2026-09-25",
    isMajor: false,
  },
  {
    id: "lpga-2026-lotte-championship",
    shortName: ["LOTTE", "CHAMP."],
    fullName: "LOTTE Championship presented by Hoakalei",
    startDate: "2026-09-30",
    isMajor: false,
  },
  {
    id: "lpga-2026-buick-lpga-shanghai",
    shortName: ["BUICK", "SHANGH"],
    fullName: "Buick LPGA Shanghai",
    startDate: "2026-10-15",
    isMajor: false,
  },
  {
    id: "lpga-2026-bmw-ladies-championship",
    shortName: ["BMW", "KOREA"],
    fullName: "BMW Ladies Championship",
    startDate: "2026-10-22",
    isMajor: false,
  },
  {
    id: "lpga-2026-maybank-championship",
    shortName: ["MAY", "BANK"],
    fullName: "Maybank Championship",
    startDate: "2026-10-29",
    isMajor: false,
  },
  {
    id: "lpga-2026-toto-japan-classic",
    shortName: ["TOTO", "JAPAN"],
    fullName: "TOTO Japan Classic",
    startDate: "2026-11-05",
    isMajor: false,
  },
  {
    id: "lpga-2026-the-annika",
    shortName: ["THE", "ANNIKA"],
    fullName: "The ANNIKA driven by Gainbridge at Pelican",
    startDate: "2026-11-12",
    isMajor: false,
  },
  {
    id: "lpga-2026-cme-tour-championship",
    shortName: ["CME", "FINALE"],
    fullName: "CME Group Tour Championship",
    startDate: "2026-11-19",
    isMajor: false,
  },
  {
    id: "lpga-2026-grant-thornton-invitational",
    shortName: ["GRANT", "THORN."],
    fullName: "Grant Thornton Invitational",
    startDate: "2026-12-11",
    isMajor: false,
  },
];

const TOUR_SEASON_BY_TITLE: Record<string, TourSeasonEvent[]> = {
  "PGA Tour": PGA_TOUR_2026_FULL_SEASON,
  "DP World Tour": DP_WORLD_TOUR_2026,
  "LIV Golf": LIV_GOLF_2026,
  "Korn Ferry": KORN_FERRY_TOUR_2026,
  "LPGA": LPGA_TOUR_2026,
};

export function getMajorChampionships(): MajorChampionship[] {
  return [...MAJOR_CHAMPIONSHIPS].sort(
    (a, b) => a.startDate.localeCompare(b.startDate) || a.id.localeCompare(b.id),
  );
}

export function getTourScheduleForTitle(title: string): TourSeasonEvent[] {
  const list = TOUR_SEASON_BY_TITLE[title];
  if (!list) return [];
  const filtered = TOUR_TITLES_EXCLUDING_MAJORS.has(title)
    ? list.filter((event) => !event.isMajor)
    : list;
  return [...filtered]
    .map(withEventLinkFields)
    .sort((a, b) => a.startDate.localeCompare(b.startDate) || a.id.localeCompare(b.id));
}
