/**
 * Generates lib/academy/shotTypeLibrary.ts from backend/academy/checkpoints.js
 * so the client's checkpoint/fault display data stays in lockstep with the
 * backend analysis engine (single source of truth).
 *
 * Run after editing checkpoints.js:  node scripts/generateAcademyLibrary.js
 */

const fs = require('fs');
const path = require('path');

const { SHOT_TYPES, SHOT_TYPE_IDS } = require('../backend/academy/checkpoints');

const client = {};
for (const id of SHOT_TYPE_IDS) {
  const def = SHOT_TYPES[id];
  client[id] = {
    id: def.id,
    label: def.label,
    swingClass: def.swingClass,
    summary: def.summary,
    phases: def.phases,
    tempo: def.tempo,
    metrics: def.metrics,
    faults: def.faults.map(({ detect, ...rest }) => rest),
    recordingTips: def.recordingTips,
  };
}

const out = `// AUTO-GENERATED by scripts/generateAcademyLibrary.js — do not edit by hand.
// Source of truth: backend/academy/checkpoints.js

import type { ShotTypeDef, ShotTypeId } from './types';

export const SHOT_TYPE_IDS: ShotTypeId[] = ${JSON.stringify(SHOT_TYPE_IDS)};

export const SHOT_TYPE_LIBRARY: Record<ShotTypeId, ShotTypeDef> = ${JSON.stringify(client, null, 2)};
`;

const dest = path.join(__dirname, '..', 'lib', 'academy', 'shotTypeLibrary.ts');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`Wrote ${dest}`);
